import { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'olive-sand',
    name: 'オリーブ＆サンド',
    description: '砂のようなベージュと落ち着いたオリーブグリーン。',
    classes: {
      app: 'bg-[#fdfbf7] text-[#4a4a33] font-serif',
      sidebar: 'bg-[#f5f3eb] border-[#e8e5d9]',
      sidebarItemActive: 'bg-[#6b705c] text-white',
      sidebarItemHover: 'hover:bg-[#e8e5d9]',
      header: 'bg-[#fdfbf7]/90 border-[#e8e5d9]',
      navLink: 'hover:text-[#6b705c]',
      hero: 'bg-[#f5f3eb]',
      heroText: 'text-[#4a4a33]',
      section: 'bg-[#fdfbf7]',
      sectionAlt: 'bg-[#f5f3eb]',
      heading: 'text-[#4a4a33] border-[#6b705c]',
      card: 'bg-[#ffffff] border-[#e8e5d9] rounded-lg shadow-sm',
      button: 'bg-[#6b705c] text-white hover:bg-[#4a4a33] rounded-md transition-colors',
    }
  },
  {
    id: 'terracotta-forest',
    name: 'テラコッタ＆フォレスト',
    description: '深い森の緑と、温かみのあるテラコッタのアクセント。',
    classes: {
      app: 'bg-[#fcfaf8] text-[#2c3e2e] font-serif',
      sidebar: 'bg-[#f2ece4] border-[#e8dfce]',
      sidebarItemActive: 'bg-[#b85d43] text-white',
      sidebarItemHover: 'hover:bg-[#e8dfce]',
      header: 'bg-[#fcfaf8]/90 border-[#e8dfce]',
      navLink: 'hover:text-[#b85d43]',
      hero: 'bg-[#f2ece4]',
      heroText: 'text-[#2c3e2e]',
      section: 'bg-[#fcfaf8]',
      sectionAlt: 'bg-[#f2ece4]',
      heading: 'text-[#2c3e2e] border-[#b85d43]',
      card: 'bg-[#ffffff] border-[#e8dfce] rounded-2xl shadow-sm',
      button: 'bg-[#b85d43] text-white hover:bg-[#8f4631] rounded-full transition-colors',
    }
  },
  {
    id: 'sage-clay',
    name: 'セージ＆クレイ',
    description: '柔らかいセージグリーンと土のブラウン。優しい印象。',
    classes: {
      app: 'bg-[#f9f9f6] text-[#5c4a3d] font-sans',
      sidebar: 'bg-[#eff0ea] border-[#e2e4dc]',
      sidebarItemActive: 'bg-[#8a9a86] text-white',
      sidebarItemHover: 'hover:bg-[#e2e4dc]',
      header: 'bg-[#f9f9f6]/90 border-[#e2e4dc]',
      navLink: 'hover:text-[#8a9a86]',
      hero: 'bg-[#eff0ea]',
      heroText: 'text-[#5c4a3d]',
      section: 'bg-[#f9f9f6]',
      sectionAlt: 'bg-[#eff0ea]',
      heading: 'text-[#5c4a3d] border-[#8a9a86]',
      card: 'bg-[#ffffff] border-[#e2e4dc] rounded-xl shadow-sm',
      button: 'bg-[#8a9a86] text-white hover:bg-[#6b7a68] rounded-lg transition-colors',
    }
  },
  {
    id: 'matcha-wood',
    name: '抹茶＆ウッド',
    description: '和を感じる抹茶色と温かい木目調のブラウン。',
    classes: {
      app: 'bg-[#faf8f5] text-[#4a3b32] font-serif',
      sidebar: 'bg-[#f0ece6] border-[#e6dfd3]',
      sidebarItemActive: 'bg-[#8c9c76] text-white',
      sidebarItemHover: 'hover:bg-[#e6dfd3]',
      header: 'bg-[#faf8f5]/90 border-[#e6dfd3]',
      navLink: 'hover:text-[#8c9c76]',
      hero: 'bg-[#f0ece6]',
      heroText: 'text-[#4a3b32]',
      section: 'bg-[#faf8f5]',
      sectionAlt: 'bg-[#f0ece6]',
      heading: 'text-[#4a3b32] border-[#8c9c76]',
      card: 'bg-[#ffffff] border-[#e6dfd3] rounded-sm shadow-sm',
      button: 'bg-[#8c9c76] text-white hover:bg-[#6a7857] rounded-sm transition-colors',
    }
  },
  {
    id: 'moss-stone',
    name: 'モス＆ストーン',
    description: '苔の緑と石のグレー。静寂で洗練された空間。',
    classes: {
      app: 'bg-[#f5f5f0] text-[#3d4035] font-sans',
      sidebar: 'bg-[#ebebe1] border-[#dcdcd1]',
      sidebarItemActive: 'bg-[#5c664d] text-white',
      sidebarItemHover: 'hover:bg-[#dcdcd1]',
      header: 'bg-[#f5f5f0]/90 border-[#dcdcd1]',
      navLink: 'hover:text-[#5c664d]',
      hero: 'bg-[#ebebe1]',
      heroText: 'text-[#3d4035]',
      section: 'bg-[#f5f5f0]',
      sectionAlt: 'bg-[#ebebe1]',
      heading: 'text-[#3d4035] border-[#5c664d]',
      card: 'bg-[#ffffff] border-[#dcdcd1] rounded-none shadow-sm',
      button: 'bg-[#5c664d] text-white hover:bg-[#424a36] rounded-none transition-colors',
    }
  },
  {
    id: 'eucalyptus-earth',
    name: 'ユーカリ＆アース',
    description: 'くすんだユーカリグリーンと豊かな大地の茶色。',
    classes: {
      app: 'bg-[#f7f9f7] text-[#4a3728] font-serif',
      sidebar: 'bg-[#eef2ee] border-[#dce3dc]',
      sidebarItemActive: 'bg-[#7a9e8e] text-white',
      sidebarItemHover: 'hover:bg-[#dce3dc]',
      header: 'bg-[#f7f9f7]/90 border-[#dce3dc]',
      navLink: 'hover:text-[#7a9e8e]',
      hero: 'bg-[#eef2ee]',
      heroText: 'text-[#4a3728]',
      section: 'bg-[#f7f9f7]',
      sectionAlt: 'bg-[#eef2ee]',
      heading: 'text-[#4a3728] border-[#7a9e8e]',
      card: 'bg-[#ffffff] border-[#dce3dc] rounded-3xl shadow-sm',
      button: 'bg-[#7a9e8e] text-white hover:bg-[#5c7a6d] rounded-full transition-colors',
    }
  },
  {
    id: 'mint-mocha',
    name: 'ミント＆モカ',
    description: '爽やかなミントグリーンと甘さのあるモカブラウン。',
    classes: {
      app: 'bg-[#fcfdfc] text-[#5c463c] font-sans',
      sidebar: 'bg-[#f2f6f4] border-[#e6eee9]',
      sidebarItemActive: 'bg-[#a3c9b8] text-[#5c463c]',
      sidebarItemHover: 'hover:bg-[#e6eee9]',
      header: 'bg-[#fcfdfc]/90 border-[#e6eee9]',
      navLink: 'hover:text-[#a3c9b8]',
      hero: 'bg-[#f2f6f4]',
      heroText: 'text-[#5c463c]',
      section: 'bg-[#fcfdfc]',
      sectionAlt: 'bg-[#f2f6f4]',
      heading: 'text-[#5c463c] border-[#a3c9b8]',
      card: 'bg-[#ffffff] border-[#e6eee9] rounded-xl shadow-sm',
      button: 'bg-[#a3c9b8] text-[#5c463c] hover:bg-[#8ab3a1] rounded-xl transition-colors',
    }
  },
  {
    id: 'leaf-sandstone',
    name: 'リーフ＆サンドストーン',
    description: '明るい葉の緑と砂岩のベージュ。活力を与える配色。',
    classes: {
      app: 'bg-[#fdfcf8] text-[#4a4036] font-serif',
      sidebar: 'bg-[#f5f2e9] border-[#e8e4d8]',
      sidebarItemActive: 'bg-[#7b9e59] text-white',
      sidebarItemHover: 'hover:bg-[#e8e4d8]',
      header: 'bg-[#fdfcf8]/90 border-[#e8e4d8]',
      navLink: 'hover:text-[#7b9e59]',
      hero: 'bg-[#f5f2e9]',
      heroText: 'text-[#4a4036]',
      section: 'bg-[#fdfcf8]',
      sectionAlt: 'bg-[#f5f2e9]',
      heading: 'text-[#4a4036] border-[#7b9e59]',
      card: 'bg-[#ffffff] border-[#e8e4d8] rounded-lg shadow-md',
      button: 'bg-[#7b9e59] text-white hover:bg-[#5c7a40] rounded-md transition-colors',
    }
  },
  {
    id: 'pine-desert',
    name: 'パイン＆デザート',
    description: '深い松の緑と砂漠の砂色。コントラストが美しい。',
    classes: {
      app: 'bg-[#fdfaf6] text-[#1e3329] font-sans',
      sidebar: 'bg-[#f5eedf] border-[#ebdcc8]',
      sidebarItemActive: 'bg-[#2c4c3b] text-[#fdfaf6]',
      sidebarItemHover: 'hover:bg-[#ebdcc8]',
      header: 'bg-[#fdfaf6]/90 border-[#ebdcc8]',
      navLink: 'hover:text-[#2c4c3b]',
      hero: 'bg-[#f5eedf]',
      heroText: 'text-[#1e3329]',
      section: 'bg-[#fdfaf6]',
      sectionAlt: 'bg-[#f5eedf]',
      heading: 'text-[#1e3329] border-[#2c4c3b]',
      card: 'bg-[#ffffff] border-[#ebdcc8] rounded-lg shadow-sm',
      button: 'bg-[#2c4c3b] text-[#fdfaf6] hover:bg-[#1a3024] rounded-lg transition-colors',
    }
  },
  {
    id: 'botanical-brick',
    name: 'ボタニカル＆ブリック',
    description: '植物の緑とレンガ色。自然の力強さを感じる組み合わせ。',
    classes: {
      app: 'bg-[#fbfaf9] text-[#3a4a3f] font-serif',
      sidebar: 'bg-[#f2efe9] border-[#e6e2dd]',
      sidebarItemActive: 'bg-[#a85c4c] text-white',
      sidebarItemHover: 'hover:bg-[#e6e2dd]',
      header: 'bg-[#fbfaf9]/90 border-[#e6e2dd]',
      navLink: 'hover:text-[#a85c4c]',
      hero: 'bg-[#f2efe9]',
      heroText: 'text-[#3a4a3f]',
      section: 'bg-[#fbfaf9]',
      sectionAlt: 'bg-[#f2efe9]',
      heading: 'text-[#3a4a3f] border-[#a85c4c]',
      card: 'bg-[#ffffff] border-[#e6e2dd] rounded-sm shadow-sm',
      button: 'bg-[#a85c4c] text-white hover:bg-[#824436] rounded-sm transition-colors',
    }
  }
];
